name: base_project_getx
version: 1.0.0+1
publish_to: none
description: Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications from a single codebase. This template is created by lehoha
homepage: https://github.com/LHHan/base_project

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

