name: base_project_getx
version: 1.0.0+1
publish_to: none
description: Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications from a single codebase. This template is created by lehoha
homepage: https://github.com/LHHan/base_project

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  logger: ^1.1.0
  get_storage: ^2.0.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.4
  flutter_native_splash: ^2.4.4
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter:
    sdk: flutter


flutter_intl:
  enabled: true

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app/fonts/
    - assets/app/icons/
    - assets/app/images/
    - assets/app/models/
    - assets/store/screenshots/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/app/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/app/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/app/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/app/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/app/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/app/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/app/fonts/Lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900


flutter_native_splash:
  color: "#ffffff"
  image: assets/app/images/im_splash.jpg
  #  branding: assets/branding-development.png
  color_dark: "#121212"
  image_dark: assets/app/images/im_splash.jpg
  #  branding_dark: assets/branding-development.png

  android_12:
    image: assets/app/images/im_splash.jpg
    icon_background_color: "#ffffff"
    image_dark: assets/app/images/im_splash.jpg
    icon_background_color_dark: "#121212"

  web: false