name: base_project_getx
version: 1.0.0+1
publish_to: none
description: Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications from a single codebase. This template is created by lehoha
homepage: https://github.com/LHHan/base_project

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  logger: ^1.1.0
  get_storage: ^2.0.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.4
  flutter:
    sdk: flutter

flutter_intl:
  enabled: true

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/app/fonts/
    - assets/app/icons/
    - assets/app/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/app/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/app/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/app/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/app/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/app/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/app/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/app/fonts/Lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900

